name: pytest

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install webdriver and poetry
      run: |
        sudo apt-get update && sudo apt-get install firefox-geckodriver
        pip install --upgrade pip && pip install --no-cache-dir poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Cache dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: poetry install -E server -E fermi
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Test with pytest
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: |
        poetry run pytest --color=yes --webdriver Firefox --headless crystal_toolkit/apps/examples/tests/
